source "https://rubygems.org"
gem "jekyll", "3.10.0"
gem "minima", "2.5.1"
gem "jekyll-sitemap", "1.4.0"
gem "jekyll-last-modified-at", "~> 1.3"
gem "webrick", "~> 1.8"
gem "base64"
gem "bigdecimal"
gem "kramdown-parser-gfm", "1.1.0"
